### ISSUE TITLE
北京官网服务器能用吗

### ISSUE THREAD

**Issue by wujianbo** [good-life/PushTalk#15]
输入用户名以后就没有反映，无法进入界面，为什么

**Comment by zhoubohui** [comment]
是不是服务器ip不对。

发件人:  wujianbo notifications@github.com
答复:  good-life/PushTalk
<reply+i-33946272-02b7370c91c11bb01c5ef18b3040f42c94d09e1f-1234977@reply.git
hub.com>
日期:  2014年5月21日 星期三 10:12
至:  good-life/PushTalk PushTalk@noreply.github.com
主题:  [PushTalk] 北京官网服务器能用吗 (#15)

输入用户名以后就没有反映，无法进入界面，为什么

—
Reply to this email directly or view it on GitHub
https://github.com/good-life/PushTalk/issues/15 .

**Comment by wujianbo** [comment]
http://111.13.48.109:10010推聊官方，没有什么问题啊

**Comment by wujianbo** [comment]
而且注册界面能进去，肯定是连接上了服务器

**Comment by wujianbo** [comment]
添加自己的服务器也是一样的结果
14/05/21 13:34:56 DEBUG web.UserRegisterServlet: action - user register
14/05/21 13:34:56 DEBUG web.MainServlet: action - main
14/05/21 13:34:56 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/E:/unitalk
/PushTalk-master/dist/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.

**Comment by wujianbo** [comment]
有人能帮忙看一下吗，目明其妙啊

**Comment by usee** [comment]
我的也是完全一样的现象, 北京官网能注册用户 ,  不能进入界面. 

自己搭建服务器, 也是一样的现象, 这是怎么回事啊? 

有人管吗?

android@Linux:~/ubuntu$ java -Dfile.encoding=UTF-8 -jar pushtalk-server-1.1.0-jar-with-dependencies.jar 
14/05/26 16:50:00 INFO server.Server: jetty-8.y.z-SNAPSHOT
14/05/26 16:50:00 INFO h2.H2Database: Begin to init H2 database.
14/05/26 16:50:00 INFO h2.H2Database: Creating connection pool
14/05/26 16:50:02 INFO h2.H2Database: Succeed to create connection pool.
14/05/26 16:50:02 DEBUG h2.H2Database: Exist tables - 0 - []
14/05/26 16:50:02 INFO h2.H2Database: Create table - channel
14/05/26 16:50:02 INFO h2.H2Database: Create table - user
14/05/26 16:50:02 INFO h2.H2Database: Create table - user_channel
14/05/26 16:50:02 INFO h2.H2Database: Create table - server_info
14/05/26 16:50:02 INFO h2.H2Database: The server_id: 5802fc94
14/05/26 16:50:02 INFO h2.TalkServiceImpl: h2 database init finished.
14/05/26 16:50:02 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:10010
14/05/26 16:51:42 DEBUG web.MainServlet: action - main
14/05/26 16:51:42 DEBUG web.MainServlet: action - main
14/05/26 16:51:56 DEBUG web.MainServlet: action - main
14/05/26 16:51:56 DEBUG web.MainServlet: action - main
14/05/26 16:53:08 DEBUG web.MainServlet: action - main
14/05/26 16:53:08 DEBUG web.MainServlet: action - main
14/05/26 16:53:27 DEBUG web.MainServlet: action - main
14/05/26 16:53:27 DEBUG web.MainServlet: action - main
14/05/26 16:53:44 DEBUG web.MainServlet: action - main
14/05/26 16:53:44 DEBUG web.MainServlet: action - main
14/05/26 17:07:13 DEBUG web.MainServlet: action - main
14/05/26 17:07:13 DEBUG web.MainServlet: action - main
14/05/26 17:08:32 DEBUG api.UserInfoServlet: api - user info
14/05/26 17:08:32 DEBUG web.MainServlet: action - main
14/05/26 17:08:32 DEBUG api.UserInfoServlet: udid - 53c563b182daf567
14/05/26 17:08:32 DEBUG freemarker.cache: Could not find template in cache, creating new one; id=["register.html"["en_US",UTF-8,parsed] ]
14/05/26 17:08:32 DEBUG freemarker.cache: Compiling FreeMarker template "register.html"["en_US",UTF-8,parsed]  from "jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html"
14/05/26 17:08:40 DEBUG web.UserRegisterServlet: action - user register
14/05/26 17:08:40 DEBUG web.MainServlet: action - main
14/05/26 17:08:40 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.
14/05/26 17:09:57 DEBUG web.UserRegisterServlet: action - user register
14/05/26 17:09:57 DEBUG web.MainServlet: action - main
14/05/26 17:09:57 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.
14/05/26 17:09:57 DEBUG web.MainServlet: action - main
14/05/26 17:09:57 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  cached copy not yet stale; using cached.
14/05/26 17:10:25 DEBUG web.UserRegisterServlet: action - user register
14/05/26 17:10:25 DEBUG web.MainServlet: action - main
14/05/26 17:10:25 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.
14/05/26 17:10:54 DEBUG web.MainServlet: action - main
14/05/26 17:10:54 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.
14/05/26 17:10:54 DEBUG api.UserInfoServlet: api - user info
14/05/26 17:10:54 DEBUG api.UserInfoServlet: udid - 53c563b182daf567
14/05/26 17:10:59 DEBUG web.UserRegisterServlet: action - user register
14/05/26 17:10:59 DEBUG web.MainServlet: action - main
14/05/26 17:10:59 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  cached copy not yet stale; using cached.
14/05/26 17:10:59 DEBUG web.MainServlet: action - main
14/05/26 17:10:59 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  cached copy not yet stale; using cached.
14/05/26 17:11:16 DEBUG web.UserRegisterServlet: action - user register
14/05/26 17:11:16 DEBUG web.MainServlet: action - main
14/05/26 17:11:16 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.
14/05/26 17:11:28 DEBUG web.UserRegisterServlet: action - user register
14/05/26 17:11:28 DEBUG web.MainServlet: action - main
14/05/26 17:11:28 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.
14/05/26 17:11:34 DEBUG web.UserRegisterServlet: action - user register
14/05/26 17:11:34 DEBUG web.MainServlet: action - main
14/05/26 17:11:34 DEBUG freemarker.cache: "register.html"["en_US",UTF-8,parsed]  using cached since jar:file:/home/android/ubuntu/pushtalk-server-1.1.0-jar-with-dependencies.jar!/org/pushtalk/server/web/template/register.html didn't change.

**Comment by Percy0016** [comment]
现在pushtalk v1有一些bug正在修复中 敬请谅解

**Comment by conan1154** [comment]
有没有什么办法可以体验下？我跑了下，也卡在注册那里了，进不去

**Comment by zhengjun516** [comment]
问题找到了，是bonecp包的问题，极光用的是bonecp-0.8.0-rc3.jar，这个包在和h2相结合时，会导致向h2 database写入数据时失败，换成bonecp-0.8.0.RELEASE.jar就可以了。

**Comment by Percy0016** [comment]
@zhengjun516 感谢您的帮助，代表极光推送感谢您的支持。
